import type { Metadata } from "next";
import { ColorSchemeScript, MantineProvider, createTheme } from '@mantine/core';
import "./globals.css";
import { FloatingAnalyzer } from '@/components/features/TechnicalAnalyzer/FloatingAnalyzer';

export const metadata: Metadata = {
  title: "AI Stock Portfolio Analyst",
  description: "Generated by AI",
};

const theme = createTheme({
  /** Put your mantine theme override here */
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme}>
          {children}
          <FloatingAnalyzer />
        </MantineProvider>
      </body>
    </html>
  );
}
